-- ===================================================================
-- FIWDEE — Massage Management & Booking System
-- Database Schema DDL (PostgreSQL 14+)
-- Aligns with 18 Entities in com.fiwdee.domain.entity.*
-- Course: CP353002 Principles of Software Design
-- ===================================================================

-- -------------------------------------------------------------------
-- 1. users: Central Identity & Authentication (Joined Table Inheritance Base)
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE,
    password_hash VARCHAR(255),
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE,
    phone_number VARCHAR(20) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_user_role CHECK (role IN ('CUSTOMER', 'RECEPTIONIST', 'THERAPIST', 'OWNER'))
);

-- -------------------------------------------------------------------
-- 2. customers: Subtype Specialization for Customer Profile
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    health_notes TEXT,
    preferred_pressure VARCHAR(50),
    registered_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- -------------------------------------------------------------------
-- 3. therapists: Subtype Specialization for Massage Therapists
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS therapists (
    id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    nickname VARCHAR(50) NOT NULL,
    bio TEXT,
    commission_rate NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
    employment_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    average_rating NUMERIC(3, 2) NOT NULL DEFAULT 0.00
);

-- -------------------------------------------------------------------
-- 4. receptionists: Subtype Specialization for Front-Desk Staff
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS receptionists (
    id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    staff_code VARCHAR(30) NOT NULL UNIQUE,
    counter_station VARCHAR(50)
);

-- -------------------------------------------------------------------
-- 5. owners: Subtype Specialization for Shop Owner / Admin
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS owners (
    id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    management_level VARCHAR(50) DEFAULT 'EXECUTIVE'
);

-- -------------------------------------------------------------------
-- 6. shops: Store Profile & Shop Settings
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- -------------------------------------------------------------------
-- 7. business_hours: Daily Opening and Closing Operating Schedule
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS business_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    day_of_week VARCHAR(10) NOT NULL,
    open_time TIME NOT NULL,
    close_time TIME NOT NULL,
    is_closed BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_business_hours_shop_day UNIQUE (shop_id, day_of_week),
    CONSTRAINT chk_day_of_week CHECK (day_of_week IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'))
);

-- -------------------------------------------------------------------
-- 8. services: Catalog of Massage Treatments
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_code VARCHAR(30) NOT NULL UNIQUE,
    service_name VARCHAR(100) NOT NULL,
    description TEXT,
    category VARCHAR(50) NOT NULL,
    required_room_type VARCHAR(30) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_required_room_type CHECK (required_room_type IN ('SINGLE', 'COUPLE', 'VIP', 'FOOT_MASSAGE'))
);

-- -------------------------------------------------------------------
-- 9. service_duration_options: Duration Tiers and Pricing per Service
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS service_duration_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    duration_minutes INTEGER NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_service_duration UNIQUE (service_id, duration_minutes),
    CONSTRAINT chk_duration_positive CHECK (duration_minutes > 0),
    CONSTRAINT chk_price_non_negative CHECK (price >= 0)
);

-- -------------------------------------------------------------------
-- 10. therapist_skills: Many-to-Many Skill Matrix with Certifications
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS therapist_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    therapist_id BIGINT NOT NULL REFERENCES therapists(id) ON DELETE CASCADE,
    service_id BIGINT NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    skill_level VARCHAR(30) DEFAULT 'STANDARD',
    is_certified BOOLEAN NOT NULL DEFAULT FALSE,
    certified_date DATE,
    CONSTRAINT uk_therapist_service_skill UNIQUE (therapist_id, service_id)
);

-- -------------------------------------------------------------------
-- 11. rooms: Physical Massage Rooms (Dynamic Resources)
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR(20) NOT NULL UNIQUE,
    room_type VARCHAR(30) NOT NULL,
    capacity INTEGER NOT NULL DEFAULT 1,
    room_status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',
    cleaning_buffer_minutes INTEGER NOT NULL DEFAULT 15,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_room_type CHECK (room_type IN ('SINGLE', 'COUPLE', 'VIP', 'FOOT_MASSAGE')),
    CONSTRAINT chk_room_status CHECK (room_status IN ('AVAILABLE', 'OCCUPIED', 'CLEANING', 'MAINTENANCE'))
);

-- -------------------------------------------------------------------
-- 12. therapist_schedules: Daily Attendance & Leave Recording
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS therapist_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    therapist_id BIGINT NOT NULL REFERENCES therapists(id) ON DELETE CASCADE,
    schedule_date DATE NOT NULL,
    is_day_off BOOLEAN NOT NULL DEFAULT FALSE,
    leave_reason VARCHAR(255),
    notes TEXT,
    CONSTRAINT uk_therapist_schedule_date UNIQUE (therapist_id, schedule_date)
);

-- -------------------------------------------------------------------
-- 13. work_shifts: Sub-shift Time Windows within a Schedule
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS work_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT NOT NULL REFERENCES therapist_schedules(id) ON DELETE CASCADE,
    shift_name VARCHAR(50) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    shift_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE'
);

-- -------------------------------------------------------------------
-- 14. bookings: Core Transaction Entity with 7 Lifecycle States & @Version
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_reference_code VARCHAR(50) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    therapist_id BIGINT REFERENCES therapists(id),
    room_id BIGINT NOT NULL REFERENCES rooms(id),
    service_id BIGINT NOT NULL REFERENCES services(id),
    duration_option_id BIGINT NOT NULL REFERENCES service_duration_options(id),
    receptionist_id BIGINT REFERENCES receptionists(id),
    start_date_time TIMESTAMP NOT NULL,
    end_date_time TIMESTAMP NOT NULL,
    total_price NUMERIC(10, 2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    booking_channel VARCHAR(50) NOT NULL,
    special_notes TEXT,
    actual_start_time TIMESTAMP,
    actual_end_time TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_booking_status CHECK (status IN ('PENDING', 'CONFIRMED', 'CHECKED_IN', 'IN_SERVICE', 'COMPLETED', 'CANCELLED', 'NO_SHOW')),
    CONSTRAINT chk_booking_time_order CHECK (end_date_time > start_date_time)
);

-- -------------------------------------------------------------------
-- 15. queue_items: Front-Desk Queue Ticket on Check-in
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS queue_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL UNIQUE REFERENCES bookings(id) ON DELETE CASCADE,
    queue_number VARCHAR(20) NOT NULL,
    queue_date DATE NOT NULL,
    check_in_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    called_time TIMESTAMP,
    queue_status VARCHAR(30) NOT NULL DEFAULT 'WAITING',
    priority_level INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_queue_date_number UNIQUE (queue_date, queue_number),
    CONSTRAINT chk_queue_status CHECK (queue_status IN ('WAITING', 'CALLED', 'IN_SERVICE', 'COMPLETED', 'CANCELLED'))
);

-- -------------------------------------------------------------------
-- 16. payments: Immutable Financial Audit Record and Receipts
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL UNIQUE REFERENCES bookings(id),
    receptionist_id BIGINT REFERENCES receptionists(id),
    payment_reference_code VARCHAR(50) NOT NULL UNIQUE,
    receipt_number VARCHAR(50) UNIQUE,
    gross_amount NUMERIC(10, 2) NOT NULL,
    discount_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    net_amount NUMERIC(10, 2) NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    payment_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    paid_at TIMESTAMP,
    transaction_note TEXT,
    CONSTRAINT chk_payment_method CHECK (payment_method IN ('CASH', 'QR_PROMPTPAY', 'CREDIT_CARD')),
    CONSTRAINT chk_payment_status CHECK (payment_status IN ('PENDING', 'COMPLETED', 'REFUNDED', 'FAILED'))
);

-- -------------------------------------------------------------------
-- 17. refunds: Immutable Audit Trails for Refund Transactions
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
    refund_reference_code VARCHAR(50) NOT NULL UNIQUE,
    refund_amount NUMERIC(10, 2) NOT NULL,
    reason VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    refunded_at TIMESTAMP,
    processed_by_staff VARCHAR(100) NOT NULL,
    CONSTRAINT chk_refund_status CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED'))
);

-- -------------------------------------------------------------------
-- 18. reviews: Customer Satisfaction Ratings and Feedback
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL UNIQUE REFERENCES bookings(id) ON DELETE CASCADE,
    overall_rating INTEGER NOT NULL,
    therapist_rating INTEGER NOT NULL,
    cleanliness_rating INTEGER NOT NULL,
    comment TEXT,
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_overall_rating CHECK (overall_rating BETWEEN 1 AND 5),
    CONSTRAINT chk_therapist_rating CHECK (therapist_rating BETWEEN 1 AND 5),
    CONSTRAINT chk_cleanliness_rating CHECK (cleanliness_rating BETWEEN 1 AND 5)
);

-- -------------------------------------------------------------------
-- Performance Indexes
-- -------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_phone ON users(phone_number);

CREATE INDEX IF NOT EXISTS idx_bookings_customer ON bookings(customer_id);
CREATE INDEX IF NOT EXISTS idx_bookings_therapist ON bookings(therapist_id);
CREATE INDEX IF NOT EXISTS idx_bookings_room ON bookings(room_id);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings(status);
CREATE INDEX IF NOT EXISTS idx_bookings_start_date ON bookings(start_date_time);

CREATE INDEX IF NOT EXISTS idx_queue_items_date_status ON queue_items(queue_date, queue_status);
CREATE INDEX IF NOT EXISTS idx_payments_reference ON payments(payment_reference_code);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(payment_status);

CREATE INDEX IF NOT EXISTS idx_therapist_schedules_date ON therapist_schedules(therapist_id, schedule_date);
